### PR TITLE
Fixes #16935: Adapt plugin build to the new separate benchmarks

### PR DESCRIPTION
**Pull request by Fdall**
https://issues.rudder.io/issues/16935

### CODE REVIEW

**Comment by Fdall** [comment]
PR updated with a new commit

**Comment by peckpeck** [comment]
150 files, 8k lines !!
Help me review ths

**Comment by VinceMacBuche** [comment]
@peckpeck Remove json file from diff, github allow you to filter on file type

**Comment by Fdall** [comment]
PR updated with a new commit

**Comment by Fdall** [comment]
PR updated with a new commit

**Comment by Fdall** [comment]
PR updated with a new commit

**Comment by Fdall** [comment]
OK, squash merging this PR

**Pull request merged**
