### PR TITLE
Fixes #26033: Openscap report cannot open in iframe since CSRF headers

### PR DESCRIPTION
**Pull request by fanf**
https://issues.rudder.io/issues/26033

So, a lot of main changes :sweat: 

The principal one is to replace antisamy by jsoup, which is much simpler, and works on whitelist, which is great since we have a good idea of what the report will have. 

I also simplified a lot of the code which was old and did strange things. Also switched to `IOResult` where I changed things. 

Finally, I added missing headers. 

It looks like that: 
image

image

### CODE REVIEW

**Comment by fanf** [comment]
PR updated with a new commit

**Comment by fanf** [comment]
PR updated with a new commit

**Review by amousset — APPROVED** [review]

**Comment by clarktsiory** [comment]
OK, squash merging this PR

**Comment by clarktsiory** [comment]
OK, merging this PR

**Comment by clarktsiory** [comment]
OK, merging this PR

**Pull request merged**
