### PR TITLE
Fixes #13037: Remove spring in plugins

### PR DESCRIPTION
**Pull request by fanf**
https://www.rudder-project.org/redmine/issues/13037

### CODE REVIEW

**Comment by VinceMacBuche** [comment]
You also need to change the build.conf of all plugins and a plugin-parent too ?

**Comment by fanf** [comment]
The version you mean? No, it's just the binary compat version (none of the plugin has new features). And I don't know for plugin-parent, what do you mean?

**Comment by fanf** [comment]
PR rebased

**Comment by amousset** [comment]
@fanf not mergeable

**Comment by fanf** [comment]
OK, merging this PR

**Pull request merged**
