### PR TITLE
Fixes #12959: Add direct token auth to the auth_modes for the Vault plugin

### PR DESCRIPTION
**Pull request by VictorQrt**
https://www.rudder-project.org/redmine/issues/12959

### CODE REVIEW

**Comment by VictorQrt** [comment]
Commit modified

**Comment by VictorQrt** [comment]
Commit modified

**Comment by VictorQrt** [comment]
Commit modified

**Comment by VictorQrt** [comment]
Commit modified

**Comment by peckpeck** [comment]
you need to run rudder-dev rebase

**Pull request merged**
