### PR TITLE
Fixes #24727: Groups node ids list in API should be filtered by tenant in plugins

### PR DESCRIPTION
**Pull request by clarktsiory**
https://issues.rudder.io/issues/24727

Fix compilation of the change-validation and scale-out-relay plugin since changes in https://github.com/Normation/rudder/pull/5608

### CODE REVIEW

**Comment by clarktsiory** [comment]
PR updated with a new commit

**Comment by clarktsiory** [comment]
PR updated with a new commit

**Comment by clarktsiory** [comment]
PR rebased

**Review by fanf — APPROVED** [review]
LGTM :+1:

**Review by fanf — APPROVED** [review]
LGTM

**Pull request merged**
