### PR TITLE
Fixes #21029: Improve integration of the Change Validation plugin in the 7.0 interface

### PR DESCRIPTION
**Pull request by RaphaelGauthier**
https://issues.rudder.io/issues/21029

### CODE REVIEW

**Comment by RaphaelGauthier** [comment]
Commit modified

**Comment by RaphaelGauthier** [comment]
Commit modified

**Comment by RaphaelGauthier** [comment]
new-change-validation-settings
new-cr-table
new-cr-details

**Comment by RaphaelGauthier** [comment]
Commit modified

**Review by VinceMacBuche — APPROVED** [review]

**Pull request merged**
