### PR TITLE
Fixes #23984: Change sequence/traverse in plugins too

### PR DESCRIPTION
**Pull request by fanf**
https://issues.rudder.io/issues/23984

### CODE REVIEW

**Review by clarktsiory — COMMENTED** [review]
Shouldn't we also fix warnings ? The plugin does not build (now that we have the `-Xfatal-warnings` option) because of these :

```
[WARNING] /home/clarkenciel/IdeaProjects/rudder-plugins/change-validation/src/main/scala/com/normation/plugins/changevalidation/api/ChangeRequestApi.scala:83: warning: Unused import
[WARNING] import net.liftweb.json.JsonAST.JValue
[WARNING]                                 ^
[WARNING] /home/clarkenciel/IdeaProjects/rudder-plugins/change-validation/src/main/scala/com/normation/plugins/changevalidation/api/ChangeRequestApi.scala:237: warning: local method concatenateJArray in method process0 is never used
[WARNING]           def concatenateJArray(a: JArray, b: JArray): JArray = {
[WARNING]               ^
[WARNING] 2 warnings
```

**Comment by fanf** [comment]
strange, I didn't got it with "make"

**Comment by fanf** [comment]
I don't have it in intellj either o_O

**Comment by fanf** [comment]
Which is normal since it's used in 7.3 - on what branch do you get the warning ?

**Comment by clarktsiory** [comment]
Oh it's because the plugin was not using my locally built Rudder version, but indeed those warnings are not actually there, it's just that they are unused since some code above uses `sequence` which is still `boxSequence` in the Rudder version

**Comment by fanf** [comment]
ok, but there is problems in master, I will see if they are trivial and can be fixed during upmerge, or need dedicated issues

**Comment by fanf** [comment]
So, merging for consistency now that parent is merged

**Review by clarktsiory — APPROVED** [review]
LGTM, and it builds successfully !

**Comment by fanf** [comment]
OK, merging this PR

**Pull request merged**
