### PR TITLE
Fixes #18630: Fix plugins build according to 6.2 changes

### PR DESCRIPTION
**Pull request by VinceMacBuche**
https://issues.rudder.io/issues/18630

### CODE REVIEW

**Comment by VinceMacBuche** [comment]
PR updated with a new commit

**Comment by VinceMacBuche** [comment]
PR updated with a new commit

**Comment by VinceMacBuche** [comment]
PR updated with a new commit

**Comment by VinceMacBuche** [comment]
PR updated with a new commit

**Review by fanf — APPROVED** [review]

**Comment by fanf** [comment]
OK, squash merging this PR

**Pull request merged**
