### PR TITLE
Fixes #17346: update openscap to use rudder_synchronize from rudder itself

### PR DESCRIPTION
**Pull request by ncharles**
https://issues.rudder.io/issues/17346

### CODE REVIEW

**Comment by ncharles** [comment]
PR updated with a new commit

**Comment by fanf** [comment]
OK, squash merging this PR

**Comment by VinceMacBuche** [comment]
OK, merging this PR

**Comment by VinceMacBuche** [comment]
OK, merging this PR

**Comment by VinceMacBuche** [comment]
OK, merging this PR

**Pull request merged**
