### PR TITLE
Fixes #23254: User management plugin incorrectly understand OIDC roles

### PR DESCRIPTION
**Pull request by fanf**
https://issues.rudder.io/issues/23254

A first PR for the problematic of dynamic role. This one is done so that it is compatible with current Rudder 7.3 and so we don't have the real configuration option for OIDC role override. So we just add a generic warning message to avoid surprise. 

This PR also correct the fact that the list of authentication providers is hard coded in user management (to provide human readable version ?) and that authentication provider out of that not-maintained list are IGNORED. 
At some point, we will have a type for providers, with their properties (does it override roles, etc), but we should never ignore unknown providers! I just removed the types, because they would likely be something else. 
This was why OIDC was not listed and so user got false information.

Message:
image
image

### CODE REVIEW

**Comment by fanf** [comment]
PR updated with a new commit

**Comment by fanf** [comment]
PR updated with a new commit

**Comment by fanf** [comment]
PR updated with a new commit

**Review by VinceMacBuche — APPROVED** [review]

**Comment by fanf** [comment]
OK, squash merging this PR

**Pull request merged**
