### PR TITLE
Fixes #23243: Hash API tokens - plugin

### PR DESCRIPTION
**Pull request by amousset**
https://issues.rudder.io/issues/23243

Matching https://github.com/Normation/rudder/pull/4971 changes.

### CODE REVIEW

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Review by fanf — APPROVED** [review]
See https://github.com/Normation/rudder/pull/4971#pullrequestreview-1580263231

**Pull request merged**
