### PR TITLE
Fixes #14534: Change validation doesn't work with elm 0.19

### PR DESCRIPTION
**Pull request by ncharles**
https://issues.rudder.io/issues/14534

### CODE REVIEW

**Comment by ncharles** [comment]
Caution: the UI is catastrophic

**Comment by fanf** [comment]
what does "Caution: the UI is catastrophic" mean?

**Comment by ncharles** [comment]
it looks like that: 
image

**Comment by fanf** [comment]
well, perhaps we should not merge that PR until the css part is solved, then?

**Comment by ncharles** [comment]
Commit modified

**Comment by ncharles** [comment]
CSS is correctly loaded now

**Pull request merged**
